class_name Chapters
extends RefCounted
## Campaign chapters (see Campaign), played in ORDER by one persistent army.
## Same format as Levels, plus:
##   deploy:          player starting cells, in order (the Lord takes the first);
##                    its size is the number of units the chapter allows.
##   recruits:        units (roster format) that join the army at this chapter.
##   objective:       see Objectives.
##   objects:         villages and chests (see BattleMap.objects).
##   reinforcements:  [{"turn": N, "units": [enemy roster entries]}]; they appear at
##                    the start of enemy phase N and act from the next one.
## Chapters have no "players": the army is deployed from the prep screen.

const ORDER: Array[String] = ["ch1", "ch2", "ch3", "ch4", "ch5"]

const DATA := {
	"ch1": {
		"name": "Chapter 1: Border Village",
		"description": "Bandits raid the border. Visit the villages before\nthe thief burns them, and rout the raiders.",
		"objective": {"type": "rout"},
		"layout": [
			"FFF..H.....FFFF",
			"FF..........FFF",
			"F.....====....F",
			"..====..=..H...",
			"..=.....=......",
			"..=..FF.=..FF..",
			"..=..FF.====...",
			"..=.........MM.",
			"T.=........MMM.",
			"..=..........M.",
		],
		"deploy": [Vector2i(1, 8), Vector2i(3, 8), Vector2i(1, 9), Vector2i(3, 9), Vector2i(4, 8), Vector2i(4, 9)],
		"objects": [
			{"type": "village", "cell": Vector2i(5, 0), "item": "Potion"},
			{"type": "village", "cell": Vector2i(11, 3), "item": "Chest Key"},
		],
		"recruits": [
			{"name": "Lord", "class": "Swordsman", "lord": true, "items": ["Iron Sword", "Potion"], "lv": 1,
				"hp": 18, "str": 5, "dex": 8, "agi": 9, "lck": 7, "def": 4, "mov": 5, "mp": 4,
				"growths": {"hp": 80, "str": 45, "dex": 50, "agi": 40, "lck": 45, "def": 30, "mp": 30},
				"bio": ["Heir to the border march."]},
			{"name": "Rider", "class": "Equestrian", "items": ["Iron Sword"], "lv": 2,
				"hp": 21, "str": 6, "dex": 6, "agi": 6, "lck": 4, "def": 6, "mov": 7, "mp": 2,
				"growths": {"hp": 75, "str": 45, "dex": 40, "agi": 35, "lck": 35, "def": 30, "mp": 15}},
			{"name": "Fighter", "class": "Axeman", "items": ["Iron Axe", "Hatchet"], "lv": 2,
				"hp": 24, "str": 7, "dex": 4, "agi": 5, "lck": 3, "def": 3, "mov": 5, "mp": 0,
				"growths": {"hp": 80, "str": 60, "dex": 40, "agi": 20, "lck": 45, "def": 25, "mp": 15}},
			{"name": "Archer", "class": "Archer", "items": ["Iron Bow"], "lv": 1,
				"hp": 18, "str": 5, "dex": 7, "agi": 6, "lck": 4, "def": 3, "mov": 5, "mp": 1,
				"growths": {"hp": 60, "str": 40, "dex": 50, "agi": 60, "lck": 50, "def": 15, "mp": 25}},
			{"name": "Cleric", "class": "Cleric", "items": ["Quarterstaff"], "spells": ["Heal"], "lv": 1,
				"hp": 16, "str": 1, "int": 5, "dex": 5, "agi": 7, "lck": 6, "def": 1, "mov": 5, "mp": 12,
				"growths": {"hp": 50, "str": 10, "int": 55, "dex": 40, "agi": 45, "lck": 55, "def": 10, "mp": 40}},
		],
		"enemies": [
			{"name": "Thief", "cell": Vector2i(14, 1), "class": "Rogue", "items": ["Knife"], "lv": 1,
				"hp": 16, "str": 3, "dex": 5, "agi": 9, "lck": 2, "def": 1, "mov": 6, "mp": 1,
				"ai": {"preset": "thief"}},
			{"name": "Bandit", "cell": Vector2i(9, 1), "class": "Brigand", "items": ["Iron Axe"], "lv": 1,
				"hp": 19, "str": 5, "dex": 1, "agi": 3, "lck": 0, "def": 2, "mov": 5, "mp": 0},
			{"name": "Bandit", "cell": Vector2i(13, 3), "class": "Brigand", "items": ["Iron Axe"], "lv": 1,
				"hp": 19, "str": 5, "dex": 1, "agi": 3, "lck": 0, "def": 2, "mov": 5, "mp": 0},
			{"name": "Bandit", "cell": Vector2i(7, 3), "class": "Brigand", "items": ["Hatchet"], "lv": 1,
				"hp": 18, "str": 5, "dex": 2, "agi": 4, "lck": 0, "def": 2, "mov": 5, "mp": 0},
			{"name": "Bandit", "cell": Vector2i(10, 6), "class": "Brigand", "items": ["Iron Axe"], "lv": 2,
				"hp": 20, "str": 6, "dex": 2, "agi": 3, "lck": 0, "def": 3, "mov": 5, "mp": 0,
				"ai": {"preset": "ambusher"}},
			{"name": "Raider", "cell": Vector2i(12, 0), "class": "Brigand", "items": ["Steel Axe"], "lv": 3,
				"hp": 22, "str": 7, "dex": 3, "agi": 3, "lck": 1, "def": 3, "mov": 5, "mp": 0,
				"ai": {"preset": "sleeper"}},
		],
	},
	"ch2": {
		"name": "Chapter 2: Hill Fort",
		"description": "The bandits hold an old hill fort. Break in and seize\nthe throne. Chests inside; a thief is after them too.",
		"objective": {"type": "seize", "cell": Vector2i(7, 0)},
		"layout": [
			"hhX___cTc___Xhh",
			"hhX_I_____I_Xhh",
			"h.X_________X.h",
			"..XXXX___XXXX..",
			"......===......",
			".F....===....F.",
			"FF.h...=...h.FF",
			"F..hh..=..hh..F",
			"....h..=..h....",
			"T......=......T",
		],
		"deploy": [Vector2i(7, 9), Vector2i(6, 9), Vector2i(8, 9), Vector2i(5, 9), Vector2i(9, 9), Vector2i(6, 8)],
		"objects": [
			{"type": "chest", "cell": Vector2i(3, 2), "item": "Silver Sword"},
			{"type": "chest", "cell": Vector2i(11, 2), "item": "Hammer"},
		],
		"recruits": [
			{"name": "Scout", "class": "Rogue", "items": ["Iron Sword", "Knife"], "lv": 3,
				"hp": 19, "str": 5, "dex": 9, "agi": 11, "lck": 6, "def": 3, "mov": 6, "mp": 2,
				"growths": {"hp": 65, "str": 35, "dex": 55, "agi": 65, "lck": 50, "def": 15, "mp": 20},
				"bio": ["A lockpick who knows the old fort's chests."]},
		],
		"enemies": [
			{"name": "Commander", "cell": Vector2i(7, 0), "class": "Hoplite", "items": ["Iron Spear", "Javelin"], "lv": 5,
				"hp": 28, "str": 8, "dex": 6, "agi": 5, "lck": 2, "def": 8, "mov": 5, "mp": 2,
				"ai": {"preset": "boss"}},
			{"name": "Thief", "cell": Vector2i(1, 2), "class": "Rogue", "items": ["Knife"], "lv": 2,
				"hp": 17, "str": 3, "dex": 6, "agi": 10, "lck": 3, "def": 1, "mov": 6, "mp": 1,
				"ai": {"preset": "thief"}},
			{"name": "Archer", "cell": Vector2i(5, 2), "class": "Archer", "items": ["Iron Bow"], "lv": 2,
				"hp": 17, "str": 5, "dex": 5, "agi": 5, "lck": 1, "def": 2, "mov": 5, "mp": 1,
				"ai": {"preset": "turret"}},
			{"name": "Archer", "cell": Vector2i(9, 2), "class": "Archer", "items": ["Iron Bow"], "lv": 2,
				"hp": 17, "str": 5, "dex": 5, "agi": 5, "lck": 1, "def": 2, "mov": 5, "mp": 1,
				"ai": {"preset": "turret"}},
			{"name": "Guard", "cell": Vector2i(6, 3), "class": "Guard", "items": ["Iron Spear"], "lv": 2,
				"hp": 22, "str": 7, "dex": 3, "agi": 2, "lck": 1, "def": 9, "mov": 4, "mp": 0,
				"ai": {"preset": "sentry"}},
			{"name": "Guard", "cell": Vector2i(8, 3), "class": "Guard", "items": ["Iron Spear"], "lv": 2,
				"hp": 22, "str": 7, "dex": 3, "agi": 2, "lck": 1, "def": 9, "mov": 4, "mp": 0,
				"ai": {"preset": "sentry"}},
			{"name": "Brigand", "cell": Vector2i(3, 6), "class": "Brigand", "items": ["Iron Axe"], "lv": 2,
				"hp": 20, "str": 6, "dex": 2, "agi": 3, "lck": 0, "def": 3, "mov": 5, "mp": 0,
				"ai": {"preset": "ambusher"}},
			{"name": "Brigand", "cell": Vector2i(11, 6), "class": "Brigand", "items": ["Iron Axe"], "lv": 2,
				"hp": 20, "str": 6, "dex": 2, "agi": 3, "lck": 0, "def": 3, "mov": 5, "mp": 0,
				"ai": {"preset": "ambusher"}},
		],
	},
	"ch3": {
		"name": "Chapter 3: The Bandit King",
		"description": "The bandit king watches from his hilltop fort.\nDefeat him and the raids end.",
		"objective": {"type": "boss", "boss": "Bandit King"},
		"layout": [
			"MMMhh....hhMMMM",
			"MMhh..#..#.hMMM",
			"Mh....##..h.T.M",
			"h....F..F...h.h",
			"...FF.~~~.FF...",
			"..F...~.~...F..",
			"......~~~......",
			".F..F......F.F.",
			"..=====...====.",
			"T.=.........=.T",
		],
		"deploy": [Vector2i(1, 9), Vector2i(3, 9), Vector2i(4, 9), Vector2i(5, 9), Vector2i(1, 8), Vector2i(0, 8), Vector2i(6, 9)],
		"objects": [
			{"type": "village", "cell": Vector2i(11, 9), "item": "Ether"},
		],
		"recruits": [
			{"name": "Pegasus", "class": "Flier", "items": ["Iron Spear", "Javelin"], "lv": 4,
				"hp": 19, "str": 6, "dex": 8, "agi": 11, "lck": 7, "def": 4, "mov": 7, "mp": 6,
				"growths": {"hp": 60, "str": 35, "dex": 50, "agi": 60, "lck": 50, "def": 15, "mp": 45},
				"bio": ["A knight of the sky, scouting for the march."]},
		],
		"enemies": [
			{"name": "Bandit King", "cell": Vector2i(12, 2), "class": "Berserker", "items": ["Steel Axe", "Hatchet"], "lv": 7,
				"hp": 32, "str": 10, "dex": 5, "agi": 6, "lck": 2, "def": 6, "mov": 5, "mp": 1,
				"ai": {"preset": "boss"}},
			{"name": "Brigand", "cell": Vector2i(10, 2), "class": "Brigand", "items": ["Iron Axe"], "lv": 3,
				"hp": 22, "str": 7, "dex": 3, "agi": 4, "lck": 1, "def": 3, "mov": 5, "mp": 0,
				"ai": {"preset": "ambusher"}},
			{"name": "Brigand", "cell": Vector2i(12, 3), "class": "Brigand", "items": ["Iron Axe"], "lv": 3,
				"hp": 22, "str": 7, "dex": 3, "agi": 4, "lck": 1, "def": 3, "mov": 5, "mp": 0,
				"ai": {"preset": "ambusher"}},
			{"name": "Archer", "cell": Vector2i(11, 1), "class": "Archer", "items": ["Iron Bow"], "lv": 3,
				"hp": 18, "str": 6, "dex": 6, "agi": 5, "lck": 1, "def": 3, "mov": 5, "mp": 1,
				"ai": {"preset": "turret"}},
			{"name": "Brigand", "cell": Vector2i(3, 2), "class": "Brigand", "items": ["Iron Axe"], "lv": 2,
				"hp": 20, "str": 6, "dex": 2, "agi": 3, "lck": 0, "def": 3, "mov": 5, "mp": 0},
			{"name": "Brigand", "cell": Vector2i(5, 3), "class": "Brigand", "items": ["Hatchet"], "lv": 2,
				"hp": 20, "str": 6, "dex": 2, "agi": 3, "lck": 0, "def": 3, "mov": 5, "mp": 0},
			{"name": "Harpy", "cell": Vector2i(9, 0), "class": "Archer", "race": "Harpy", "items": ["Iron Bow"], "lv": 3,
				"hp": 18, "str": 5, "dex": 6, "agi": 9, "lck": 3, "def": 2, "mov": 6, "mp": 3},
		],
	},
	"ch4": {
		"name": "Chapter 4: The Siege",
		"description": "An army besieges the town. Hold the town hall for\n7 turns; if any enemy reaches it, the town falls.",
		"objective": {"type": "defend", "turns": 7, "cell": Vector2i(6, 3)},
		"layout": [
			"FFF.........FFF",
			"F..XXXXXXX....F",
			"...X_H_H_X.....",
			"...X__T__X.....",
			"...X_____X.....",
			"...XXX_XXX.....",
			".....======....",
			"..F........hh..",
			".FF....F....h..",
			"...............",
		],
		"deploy": [Vector2i(6, 4), Vector2i(4, 3), Vector2i(8, 3), Vector2i(4, 2), Vector2i(8, 2), Vector2i(5, 4), Vector2i(7, 4)],
		"objects": [],
		"recruits": [
			{"name": "Guard", "class": "Guard", "items": ["Iron Spear", "Javelin"], "lv": 4,
				"hp": 25, "str": 8, "dex": 5, "agi": 3, "lck": 3, "def": 11, "mov": 4, "mp": 1,
				"growths": {"hp": 90, "str": 40, "dex": 30, "agi": 25, "lck": 30, "def": 55, "mp": 10},
				"bio": ["Captain of the town watch."]},
			{"name": "Mage", "class": "Mage", "items": ["Quarterstaff"], "spells": ["Fire", "Firestorm"], "lv": 4,
				"hp": 18, "str": 1, "int": 8, "dex": 6, "agi": 7, "lck": 4, "def": 2, "mov": 5, "mp": 16,
				"growths": {"hp": 55, "str": 5, "int": 60, "dex": 45, "agi": 45, "lck": 30, "def": 15, "mp": 50},
				"bio": ["A scholar who stayed behind to defend the town."]},
		],
		"enemies": [
			{"name": "Soldier", "cell": Vector2i(13, 2), "class": "Footman", "items": ["Iron Spear"], "lv": 3,
				"hp": 20, "str": 6, "dex": 4, "agi": 4, "lck": 1, "def": 5, "mov": 5, "mp": 1,
				"ai": {"move": "goto", "destination": Vector2i(6, 3)}},
			{"name": "Soldier", "cell": Vector2i(12, 4), "class": "Footman", "items": ["Iron Spear"], "lv": 3,
				"hp": 20, "str": 6, "dex": 4, "agi": 4, "lck": 1, "def": 5, "mov": 5, "mp": 1},
			{"name": "Brigand", "cell": Vector2i(13, 6), "class": "Brigand", "items": ["Iron Axe"], "lv": 3,
				"hp": 22, "str": 7, "dex": 3, "agi": 4, "lck": 1, "def": 3, "mov": 5, "mp": 0},
			{"name": "Archer", "cell": Vector2i(11, 7), "class": "Archer", "items": ["Iron Bow"], "lv": 3,
				"hp": 18, "str": 6, "dex": 6, "agi": 5, "lck": 1, "def": 3, "mov": 5, "mp": 1},
			{"name": "Brigand", "cell": Vector2i(12, 8), "class": "Brigand", "items": ["Hatchet"], "lv": 3,
				"hp": 22, "str": 7, "dex": 3, "agi": 4, "lck": 1, "def": 3, "mov": 5, "mp": 0},
		],
		"reinforcements": [
			{"turn": 2, "units": [
				{"name": "Soldier", "cell": Vector2i(14, 3), "class": "Footman", "items": ["Iron Spear"], "lv": 3,
					"hp": 20, "str": 6, "dex": 4, "agi": 4, "lck": 1, "def": 5, "mov": 5, "mp": 1,
					"ai": {"move": "goto", "destination": Vector2i(6, 3)}},
				{"name": "Brigand", "cell": Vector2i(14, 5), "class": "Brigand", "items": ["Iron Axe"], "lv": 3,
					"hp": 22, "str": 7, "dex": 3, "agi": 4, "lck": 1, "def": 3, "mov": 5, "mp": 0},
			]},
			{"turn": 4, "units": [
				{"name": "Nomad", "cell": Vector2i(14, 1), "class": "Nomad", "items": ["Iron Bow"], "lv": 3,
					"hp": 19, "str": 5, "dex": 6, "agi": 7, "lck": 2, "def": 4, "mov": 7, "mp": 0},
				{"name": "Cavalry", "cell": Vector2i(14, 7), "class": "Cavalry", "items": ["Iron Spear"], "lv": 3,
					"hp": 22, "str": 7, "dex": 5, "agi": 6, "lck": 2, "def": 6, "mov": 7, "mp": 0,
					"ai": {"move": "goto", "destination": Vector2i(6, 3)}},
			]},
			{"turn": 6, "units": [
				{"name": "Soldier", "cell": Vector2i(14, 2), "class": "Footman", "items": ["Iron Spear"], "lv": 4,
					"hp": 21, "str": 7, "dex": 4, "agi": 4, "lck": 1, "def": 6, "mov": 5, "mp": 1},
				{"name": "Brigand", "cell": Vector2i(14, 4), "class": "Brigand", "items": ["Steel Axe"], "lv": 4,
					"hp": 24, "str": 8, "dex": 3, "agi": 4, "lck": 1, "def": 4, "mov": 5, "mp": 0},
				{"name": "Soldier", "cell": Vector2i(14, 6), "class": "Footman", "items": ["Iron Spear"], "lv": 4,
					"hp": 21, "str": 7, "dex": 4, "agi": 4, "lck": 1, "def": 6, "mov": 5, "mp": 1,
					"ai": {"move": "goto", "destination": Vector2i(6, 3)}},
			]},
		],
	},
	"ch5": {
		"name": "Chapter 5: Flight from the Keep",
		"description": "Betrayed inside the castle. Get your Lord out\nthrough the gate to the south.",
		"objective": {"type": "escape", "cells": [Vector2i(6, 9), Vector2i(7, 9), Vector2i(8, 9)]},
		"layout": [
			"XXXXXXXXXXXXXXX",
			"X_____ccc_____X",
			"X__I__ccc__I__X",
			"XXX_X_ccc_X_XXX",
			"X_OO__ccc__OO_X",
			"X_OO|_ccc_|OO_X",
			"X___|_ccc_|___X",
			"X__I__ccc__I__X",
			"X_____ccc_____X",
			"XXXXXX___XXXXXX",
		],
		"deploy": [Vector2i(7, 1), Vector2i(6, 1), Vector2i(8, 1), Vector2i(5, 1), Vector2i(9, 1), Vector2i(6, 2), Vector2i(8, 2)],
		"objects": [
			{"type": "chest", "cell": Vector2i(1, 1), "item": "Silver Bow"},
		],
		"recruits": [
			{"name": "Dancer", "class": "Performer", "items": ["Iron Sword", "Potion"], "lv": 5,
				"hp": 17, "str": 2, "dex": 5, "agi": 12, "lck": 9, "def": 2, "mov": 5, "mp": 4,
				"growths": {"hp": 60, "str": 10, "dex": 30, "agi": 65, "lck": 60, "def": 15, "mp": 35},
				"bio": ["A court dancer who chose your side."]},
		],
		"enemies": [
			{"name": "Wraith", "cell": Vector2i(1, 7), "class": "Wraith", "items": ["Iron Sword"], "lv": 4,
				"hp": 20, "str": 7, "dex": 6, "agi": 8, "lck": 0, "def": 3, "mov": 5, "mp": 6},
			{"name": "Wraith", "cell": Vector2i(13, 7), "class": "Wraith", "items": ["Iron Sword"], "lv": 4,
				"hp": 20, "str": 7, "dex": 6, "agi": 8, "lck": 0, "def": 3, "mov": 5, "mp": 6},
			{"name": "Guard", "cell": Vector2i(5, 8), "class": "Guard", "items": ["Iron Spear"], "lv": 4,
				"hp": 24, "str": 8, "dex": 4, "agi": 2, "lck": 1, "def": 10, "mov": 4, "mp": 0,
				"ai": {"preset": "sentry"}},
			{"name": "Guard", "cell": Vector2i(9, 8), "class": "Guard", "items": ["Iron Spear"], "lv": 4,
				"hp": 24, "str": 8, "dex": 4, "agi": 2, "lck": 1, "def": 10, "mov": 4, "mp": 0,
				"ai": {"preset": "sentry"}},
			{"name": "Archer", "cell": Vector2i(3, 7), "class": "Archer", "items": ["Iron Bow"], "lv": 4,
				"hp": 19, "str": 6, "dex": 6, "agi": 5, "lck": 2, "def": 3, "mov": 5, "mp": 1,
				"ai": {"preset": "turret"}},
			{"name": "Archer", "cell": Vector2i(11, 7), "class": "Archer", "items": ["Iron Bow"], "lv": 4,
				"hp": 19, "str": 6, "dex": 6, "agi": 5, "lck": 2, "def": 3, "mov": 5, "mp": 1,
				"ai": {"preset": "turret"}},
			{"name": "Harpy", "cell": Vector2i(2, 4), "class": "Archer", "race": "Harpy", "items": ["Iron Bow"], "lv": 4,
				"hp": 19, "str": 5, "dex": 6, "agi": 9, "lck": 3, "def": 2, "mov": 6, "mp": 3,
				"ai": {"preset": "ambusher"}},
		],
		"reinforcements": [
			{"turn": 3, "units": [
				{"name": "Wraith", "cell": Vector2i(1, 1), "class": "Wraith", "items": ["Iron Sword"], "lv": 4,
					"hp": 20, "str": 7, "dex": 6, "agi": 8, "lck": 0, "def": 3, "mov": 5, "mp": 6},
				{"name": "Wraith", "cell": Vector2i(13, 1), "class": "Wraith", "items": ["Iron Sword"], "lv": 4,
					"hp": 20, "str": 7, "dex": 6, "agi": 8, "lck": 0, "def": 3, "mov": 5, "mp": 6},
			]},
		],
	},
}
