class_name Levels
extends RefCounted
## Playable maps: terrain layout plus both rosters. The level select screen sets
## `selected` and the battle scene loads it. The default is the first level,
## which the test suite relies on.
##
## Terrain keys are defined in BattleMap.TERRAIN; unit entries are read by Unit.create().

static var selected := "river_crossing"

const ORDER: Array[String] = ["river_crossing", "coastal_raid"]

const DATA := {
	"river_crossing": {
		"name": "River Crossing",
		"description": "The original test map: a mixed army, magic, forts\nand every enemy behavior preset.",
		"layout": [
			"....F..~....FT.",
			".FF....~.....F.",
			"...............",
			"..MM...~..MM...",
			"..M....~...M...",
			"....F..~..F....",
			"...............",
			".FF....~...FF..",
			"..F....~....FT.",
			".T.....~.......",
		],
		"players": [
			{"name": "Lord", "cell": Vector2i(1, 4), "lord": true, "items": ["Iron Sword", "Knife", "Potion"], "lv": 1,
				"spells": ["Earth Spike"],
				"hp": 18, "str": 5, "int": 2, "dex": 8, "agi": 9, "lck": 7, "def": 4, "mov": 5, "mp": 8,
				"growths": {"hp": 80, "str": 45, "int": 20, "dex": 50, "agi": 40, "lck": 45, "def": 30, "mp": 30}},
			{"name": "Fighter", "cell": Vector2i(2, 2), "items": ["Iron Axe", "Hatchet"], "lv": 2,
				"hp": 24, "str": 7, "dex": 4, "agi": 5, "lck": 3, "def": 3, "mp": 0, "mov": 5,
				"growths": {"hp": 80, "str": 60, "dex": 40, "agi": 20, "lck": 45, "def": 25, "mp": 15}},
			{"name": "Knight", "cell": Vector2i(2, 6), "items": ["Iron Lance", "Javelin", "Potion"], "lv": 1,
				"hp": 22, "str": 7, "dex": 4, "agi": 2, "lck": 2, "def": 9, "mp": 1, "mov": 4,
				"growths": {"hp": 90, "str": 40, "dex": 30, "agi": 30, "lck": 35, "def": 55, "mp": 15}},
			{"name": "Archer", "cell": Vector2i(1, 6), "items": ["Iron Bow"], "lv": 1,
				"hp": 18, "str": 5, "dex": 7, "agi": 6, "lck": 4, "def": 3, "mp": 1, "mov": 5,
				"growths": {"hp": 60, "str": 40, "dex": 50, "agi": 60, "lck": 50, "def": 15, "mp": 25}},
			{"name": "Cleric", "cell": Vector2i(0, 5), "spells": ["Heal"], "lv": 1,
				"hp": 16, "str": 1, "int": 5, "dex": 5, "agi": 7, "lck": 6, "def": 1, "mov": 5, "mp": 12,
				"growths": {"hp": 50, "str": 10, "int": 55, "dex": 40, "agi": 45, "lck": 55, "def": 10, "mp": 40}},
			{"name": "Mage", "cell": Vector2i(0, 3), "spells": ["Fire", "Firestorm"], "lv": 1,
				"hp": 16, "str": 1, "int": 6, "dex": 5, "agi": 6, "lck": 3, "def": 2, "mov": 5, "mp": 14,
				"growths": {"hp": 55, "str": 5, "int": 60, "dex": 45, "agi": 45, "lck": 30, "def": 15, "mp": 50}},
			{"name": "Dancer", "cell": Vector2i(0, 7), "dancer": true, "items": ["Potion"], "lv": 1,
				"hp": 15, "str": 1, "dex": 3, "agi": 10, "lck": 8, "def": 1, "mp": 3, "mov": 5,
				"growths": {"hp": 60, "str": 10, "dex": 30, "agi": 65, "lck": 60, "def": 15, "mp": 35}},
		],
		"enemies": [
			{"name": "Thief", "cell": Vector2i(14, 1), "items": ["Knife"], "lv": 1,
				"hp": 16, "str": 3, "dex": 5, "agi": 9, "lck": 2, "def": 1, "mp": 1, "mov": 6,
				"ai": {"preset": "coward", "targeting": "weakest"}},
			{"name": "Brigand", "cell": Vector2i(12, 2), "items": ["Iron Axe", "Hatchet"], "lv": 2,
				"hp": 20, "str": 5, "dex": 1, "agi": 4, "lck": 0, "def": 3, "mp": 0, "mov": 5},
			{"name": "Soldier", "cell": Vector2i(13, 4), "items": ["Iron Lance", "Javelin"], "lv": 1,
				"hp": 18, "str": 5, "dex": 3, "agi": 4, "lck": 1, "def": 4, "mp": 1, "mov": 5,
				"ai": {"preset": "sentry"}},
			{"name": "Archer", "cell": Vector2i(14, 5), "items": ["Iron Bow"], "lv": 2,
				"hp": 17, "str": 5, "dex": 4, "agi": 5, "lck": 1, "def": 2, "mp": 1, "mov": 5,
				"ai": {"preset": "turret"}},
			{"name": "Brigand", "cell": Vector2i(12, 6), "items": ["Steel Axe"], "lv": 3,
				"hp": 21, "str": 6, "dex": 2, "agi": 3, "lck": 0, "def": 2, "mp": 0, "mov": 5,
				"ai": {"preset": "sleeper", "wake": {"in_threat": true, "attacked": true, "group": "south"}}},
			{"name": "Cleric", "cell": Vector2i(14, 7), "spells": ["Heal"], "lv": 2,
				"hp": 15, "str": 1, "int": 4, "dex": 4, "agi": 6, "lck": 4, "def": 1, "mov": 5, "mp": 10,
				"ai": {"move": "hold", "wake": {"group": "south"}}},
			{"name": "Mage", "cell": Vector2i(13, 6), "spells": ["Fire", "Firestorm"], "lv": 2,
				"hp": 15, "str": 1, "int": 5, "dex": 4, "agi": 5, "lck": 1, "def": 1, "mov": 5, "mp": 12,
				"ai": {"preset": "ambusher", "priority": ["Cleric", "Dancer"]}},
			{"name": "Mercenary", "cell": Vector2i(13, 8), "items": ["Killing Edge", "Iron Sword"], "lv": 3,
				"hp": 19, "str": 4, "dex": 6, "agi": 8, "lck": 2, "def": 3, "mp": 1, "mov": 5,
				"ai": {"preset": "boss"}},
		],
	},
	"coastal_raid": {
		"name": "Coastal Raid",
		"description": "Movement types: cavalry, a pegasus, an outlaw and a siren\nvs. galleys, a naga and a wyvern. The boss holds an island fort.",
		"layout": [
			"..FFF...~..WWWW",
			".T.FF...~.SWWWW",
			"....FF.....SWWW",
			"..M.FF..~.SWWWW",
			"..M..F..~.SWSTW",
			"..M.FF..~.SWSSW",
			"....FF..~..WWWW",
			".FF.......SWWWW",
			".FF.....~.SSWWW",
			"........~~~WWWW",
		],
		"players": [
			{"name": "Lord", "cell": Vector2i(1, 4), "lord": true, "items": ["Iron Sword", "Knife", "Potion"], "lv": 2,
				"spells": ["Earth Spike"],
				"hp": 20, "str": 6, "int": 2, "dex": 8, "agi": 9, "lck": 7, "def": 5, "mov": 5, "mp": 8,
				"growths": {"hp": 80, "str": 45, "int": 20, "dex": 50, "agi": 40, "lck": 45, "def": 30, "mp": 30}},
			{"name": "Cavalier", "cell": Vector2i(1, 2), "move": "horse", "items": ["Iron Sword", "Iron Lance"], "lv": 2,
				"hp": 22, "str": 7, "dex": 6, "agi": 6, "lck": 4, "def": 6, "mp": 2, "mov": 7,
				"growths": {"hp": 75, "str": 45, "dex": 40, "agi": 35, "lck": 35, "def": 30, "mp": 15}},
			{"name": "Pegasus", "cell": Vector2i(0, 3), "move": "flying", "items": ["Iron Lance", "Javelin"], "lv": 2,
				"hp": 17, "str": 5, "dex": 7, "agi": 10, "lck": 6, "def": 3, "mp": 6, "mov": 7,
				"growths": {"hp": 60, "str": 35, "dex": 50, "agi": 60, "lck": 50, "def": 15, "mp": 45}},
			{"name": "Outlaw", "cell": Vector2i(1, 6), "move": "rogue", "items": ["Iron Sword", "Knife"], "lv": 2,
				"hp": 19, "str": 5, "dex": 9, "agi": 11, "lck": 6, "def": 3, "mp": 2, "mov": 6,
				"growths": {"hp": 65, "str": 35, "dex": 55, "agi": 65, "lck": 50, "def": 15, "mp": 20}},
			{"name": "Siren", "cell": Vector2i(7, 8), "move": "mermaid", "items": ["Javelin", "Iron Lance"], "lv": 2,
				"hp": 20, "str": 6, "dex": 6, "agi": 7, "lck": 5, "def": 4, "mp": 5, "mov": 5,
				"growths": {"hp": 70, "str": 40, "dex": 45, "agi": 45, "lck": 40, "def": 25, "mp": 35}},
			{"name": "Cleric", "cell": Vector2i(0, 5), "spells": ["Heal"], "lv": 1,
				"hp": 16, "str": 1, "int": 5, "dex": 5, "agi": 7, "lck": 6, "def": 1, "mov": 5, "mp": 12,
				"growths": {"hp": 50, "str": 10, "int": 55, "dex": 40, "agi": 45, "lck": 55, "def": 10, "mp": 40}},
		],
		"enemies": [
			{"name": "Bandit", "cell": Vector2i(5, 4), "move": "rogue", "items": ["Iron Axe"], "lv": 2,
				"hp": 21, "str": 6, "dex": 3, "agi": 6, "lck": 1, "def": 3, "mp": 0, "mov": 6,
				"ai": {"preset": "ambusher"}},
			{"name": "Bandit", "cell": Vector2i(2, 7), "move": "rogue", "items": ["Iron Axe", "Hatchet"], "lv": 2,
				"hp": 21, "str": 6, "dex": 3, "agi": 6, "lck": 1, "def": 3, "mp": 0, "mov": 6,
				"ai": {"preset": "sleeper"}},
			{"name": "Lancer", "cell": Vector2i(9, 2), "move": "horse", "items": ["Iron Lance"], "lv": 2,
				"hp": 20, "str": 6, "dex": 5, "agi": 5, "lck": 2, "def": 5, "mp": 1, "mov": 7},
			{"name": "Wyvern", "cell": Vector2i(10, 0), "move": "flying", "items": ["Iron Axe"], "lv": 3,
				"hp": 23, "str": 7, "dex": 4, "agi": 5, "lck": 1, "def": 7, "mp": 0, "mov": 7},
			{"name": "Naga", "cell": Vector2i(8, 4), "move": "mermaid", "items": ["Javelin"], "lv": 2,
				"hp": 18, "str": 5, "dex": 6, "agi": 7, "lck": 3, "def": 3, "mp": 4, "mov": 5,
				"ai": {"preset": "ambusher"}},
			{"name": "Galley", "cell": Vector2i(12, 1), "move": "ship", "items": ["Iron Bow"], "lv": 2,
				"hp": 24, "str": 6, "dex": 5, "agi": 2, "lck": 0, "def": 6, "mp": 0, "mov": 4},
			{"name": "Galley", "cell": Vector2i(13, 7), "move": "ship", "items": ["Iron Bow"], "lv": 2,
				"hp": 24, "str": 6, "dex": 5, "agi": 2, "lck": 0, "def": 6, "mp": 0, "mov": 4},
			{"name": "Captain", "cell": Vector2i(13, 4), "items": ["Steel Axe", "Hatchet"], "lv": 4,
				"hp": 26, "str": 8, "dex": 5, "agi": 5, "lck": 2, "def": 6, "mp": 2, "mov": 5,
				"ai": {"preset": "boss"}},
		],
	},
}


static func get_level(id: String) -> Dictionary:
	return DATA[id]
