class_name Levels
extends RefCounted
## Playable maps: terrain layout plus both rosters. The level select screen sets
## `selected` and the battle scene loads it. The default is the first level,
## which the test suite relies on.
##
## Terrain keys are defined in BattleMap.TERRAIN; unit entries are read by Unit.create().
## Every unit needs a "class" (see Classes), which sets its movement and weapons.

static var selected := "river_crossing"
## Set by the level select to resume the suspended battle instead of starting fresh.
static var resume := false

const ORDER: Array[String] = ["river_crossing", "coastal_raid", "desert_outpost", "frozen_pass", "castle_keep", "ruined_fort"]

const DATA := {
	"river_crossing": {
		"name": "River Crossing",
		"description": "The original test map: a mixed army, magic, forts,\nInspire and every enemy behavior preset.",
		"layout": [
			"....F..~....FT.",
			".FF....~.....F.",
			"...............",
			"..MM...~..MM...",
			"..M....~...M...",
			"....F..~..F....",
			"...............",
			".FF....~...FF..",
			"..F....~....FT.",
			".T.....~.......",
		],
		"players": [
			{"name": "Lord", "cell": Vector2i(1, 4), "class": "Swordsman", "lord": true, "items": ["Iron Sword", "Knife", "Potion"], "lv": 1,
				"spells": ["Earth Spike"],
				"bio": ["Raised in the river villages; took up the sword when the brigands came.",
					"Swore to hold the river crossing."],
				"hp": 18, "str": 5, "int": 2, "dex": 8, "agi": 9, "lck": 7, "def": 4, "mov": 5, "mp": 8,
				"growths": {"hp": 80, "str": 45, "int": 20, "dex": 50, "agi": 40, "lck": 45, "def": 30, "mp": 30}},
			{"name": "Fighter", "cell": Vector2i(2, 2), "class": "Axeman", "items": ["Iron Axe", "Hatchet"], "lv": 2,
				"hp": 24, "str": 7, "dex": 4, "agi": 5, "lck": 3, "def": 3, "mp": 0, "mov": 5,
				"growths": {"hp": 80, "str": 60, "dex": 40, "agi": 20, "lck": 45, "def": 25, "mp": 15}},
			{"name": "Knight", "cell": Vector2i(2, 6), "class": "Guard", "items": ["Iron Spear", "Javelin", "Potion"], "lv": 1,
				"hp": 22, "str": 7, "dex": 4, "agi": 2, "lck": 2, "def": 9, "mp": 1, "mov": 4,
				"growths": {"hp": 90, "str": 40, "dex": 30, "agi": 30, "lck": 35, "def": 55, "mp": 15}},
			{"name": "Archer", "cell": Vector2i(1, 6), "class": "Archer", "items": ["Iron Bow"], "lv": 1,
				"hp": 18, "str": 5, "dex": 7, "agi": 6, "lck": 4, "def": 3, "mp": 1, "mov": 5,
				"growths": {"hp": 60, "str": 40, "dex": 50, "agi": 60, "lck": 50, "def": 15, "mp": 25}},
			{"name": "Cleric", "cell": Vector2i(0, 5), "class": "Cleric", "items": ["Quarterstaff"], "spells": ["Heal"], "lv": 1,
				"hp": 16, "str": 1, "int": 5, "dex": 5, "agi": 7, "lck": 6, "def": 1, "mov": 5, "mp": 12,
				"growths": {"hp": 50, "str": 10, "int": 55, "dex": 40, "agi": 45, "lck": 55, "def": 10, "mp": 40}},
			{"name": "Mage", "cell": Vector2i(0, 3), "class": "Mage", "items": ["Quarterstaff", "Ether"], "spells": ["Fire", "Firestorm"], "lv": 1,
				"hp": 16, "str": 1, "int": 6, "dex": 5, "agi": 6, "lck": 3, "def": 2, "mov": 5, "mp": 14,
				"growths": {"hp": 55, "str": 5, "int": 60, "dex": 45, "agi": 45, "lck": 30, "def": 15, "mp": 50}},
			{"name": "Dancer", "cell": Vector2i(0, 7), "class": "Performer", "items": ["Potion"], "lv": 1,
				"hp": 15, "str": 1, "dex": 3, "agi": 10, "lck": 8, "def": 1, "mp": 3, "mov": 5,
				"growths": {"hp": 60, "str": 10, "dex": 30, "agi": 65, "lck": 60, "def": 15, "mp": 35}},
			{"name": "Bannerman", "cell": Vector2i(0, 4), "class": "Bannerman", "items": ["Iron Spear"], "lv": 1,
				"hp": 20, "str": 5, "dex": 5, "agi": 4, "lck": 5, "def": 5, "mp": 2, "mov": 5,
				"growths": {"hp": 75, "str": 35, "dex": 40, "agi": 30, "lck": 50, "def": 35, "mp": 20}},
		],
		"enemies": [
			{"name": "Thief", "cell": Vector2i(14, 1), "class": "Rogue", "items": ["Knife"], "lv": 1,
				"hp": 16, "str": 3, "dex": 5, "agi": 9, "lck": 2, "def": 1, "mp": 1, "mov": 6,
				"ai": {"preset": "coward", "targeting": "weakest"}},
			{"name": "Brigand", "cell": Vector2i(12, 2), "class": "Brigand", "items": ["Iron Axe", "Hatchet"], "lv": 2,
				"hp": 20, "str": 5, "dex": 1, "agi": 4, "lck": 0, "def": 3, "mp": 0, "mov": 5},
			{"name": "Soldier", "cell": Vector2i(13, 4), "class": "Footman", "items": ["Iron Spear", "Javelin"], "lv": 1,
				"hp": 18, "str": 5, "dex": 3, "agi": 4, "lck": 1, "def": 4, "mp": 1, "mov": 5,
				"ai": {"preset": "sentry"}},
			{"name": "Archer", "cell": Vector2i(14, 5), "class": "Archer", "items": ["Iron Bow"], "lv": 2,
				"hp": 17, "str": 5, "dex": 4, "agi": 5, "lck": 1, "def": 2, "mp": 1, "mov": 5,
				"ai": {"preset": "turret"}},
			{"name": "Brigand", "cell": Vector2i(12, 6), "class": "Brigand", "items": ["Steel Axe"], "lv": 3,
				"hp": 21, "str": 6, "dex": 2, "agi": 3, "lck": 0, "def": 2, "mp": 0, "mov": 5,
				"ai": {"preset": "sleeper", "wake": {"in_threat": true, "attacked": true, "group": "south"}}},
			{"name": "Cleric", "cell": Vector2i(14, 7), "class": "Cleric", "spells": ["Heal"], "lv": 2,
				"hp": 15, "str": 1, "int": 4, "dex": 4, "agi": 6, "lck": 4, "def": 1, "mov": 5, "mp": 10,
				"ai": {"move": "hold", "wake": {"group": "south"}}},
			{"name": "Mage", "cell": Vector2i(13, 6), "class": "Mage", "items": ["Quarterstaff"], "spells": ["Fire", "Firestorm"], "lv": 2,
				"hp": 15, "str": 1, "int": 5, "dex": 4, "agi": 5, "lck": 1, "def": 1, "mov": 5, "mp": 12,
				"ai": {"preset": "ambusher", "priority": ["Cleric", "Dancer"]}},
			{"name": "Mercenary", "cell": Vector2i(13, 8), "class": "Swordsmaster", "items": ["Killing Edge", "Iron Sword"], "lv": 3,
				"hp": 19, "str": 4, "dex": 6, "agi": 8, "lck": 2, "def": 3, "mp": 1, "mov": 5,
				"ai": {"preset": "boss"}},
		],
	},
	"coastal_raid": {
		"name": "Coastal Raid",
		"description": "Movement types and ships: Board your Galley to ferry\ntroops to the island fort the Swashbuckler boss holds.",
		"layout": [
			"..FFF...~..WWWW",
			".T.FF...~.SWWWW",
			"....FF.....SWWW",
			"..M.FF..~.SWWWW",
			"..M..F..~.SWSTW",
			"..M.FF..~.SWSSW",
			"....FF..~..WWWW",
			".FF.......SWWWW",
			".FF.....~.SSWWW",
			"........~~~WWWW",
		],
		"players": [
			{"name": "Lord", "cell": Vector2i(1, 4), "class": "Swordsman", "lord": true, "items": ["Iron Sword", "Knife", "Potion"], "lv": 2,
				"spells": ["Earth Spike"],
				"hp": 20, "str": 6, "int": 2, "dex": 8, "agi": 9, "lck": 7, "def": 5, "mov": 5, "mp": 8,
				"growths": {"hp": 80, "str": 45, "int": 20, "dex": 50, "agi": 40, "lck": 45, "def": 30, "mp": 30}},
			{"name": "Cavalier", "cell": Vector2i(1, 2), "class": "Equestrian", "items": ["Iron Sword", "Knife"], "lv": 2,
				"hp": 22, "str": 7, "dex": 6, "agi": 6, "lck": 4, "def": 6, "mp": 2, "mov": 7,
				"growths": {"hp": 75, "str": 45, "dex": 40, "agi": 35, "lck": 35, "def": 30, "mp": 15}},
			{"name": "Pegasus", "cell": Vector2i(0, 3), "class": "Flier", "items": ["Iron Spear", "Javelin"], "lv": 2,
				"hp": 17, "str": 5, "dex": 7, "agi": 10, "lck": 6, "def": 3, "mp": 6, "mov": 7,
				"growths": {"hp": 60, "str": 35, "dex": 50, "agi": 60, "lck": 50, "def": 15, "mp": 45}},
			{"name": "Outlaw", "cell": Vector2i(1, 6), "class": "Rogue", "items": ["Iron Sword", "Knife"], "lv": 2,
				"hp": 19, "str": 5, "dex": 9, "agi": 11, "lck": 6, "def": 3, "mp": 2, "mov": 6,
				"growths": {"hp": 65, "str": 35, "dex": 55, "agi": 65, "lck": 50, "def": 15, "mp": 20}},
			{"name": "Siren", "cell": Vector2i(7, 8), "class": "Footman", "race": "Naga", "items": ["Javelin", "Iron Spear"], "lv": 2,
				"hp": 20, "str": 6, "dex": 6, "agi": 7, "lck": 5, "def": 4, "mp": 5, "mov": 5,
				"growths": {"hp": 70, "str": 40, "dex": 45, "agi": 45, "lck": 40, "def": 25, "mp": 35}},
			{"name": "Cleric", "cell": Vector2i(0, 5), "class": "Cleric", "items": ["Quarterstaff"], "spells": ["Heal"], "lv": 1,
				"hp": 16, "str": 1, "int": 5, "dex": 5, "agi": 7, "lck": 6, "def": 1, "mov": 5, "mp": 12,
				"growths": {"hp": 50, "str": 10, "int": 55, "dex": 40, "agi": 45, "lck": 55, "def": 10, "mp": 40}},
			{"name": "Corsair", "cell": Vector2i(7, 9), "class": "Corsair", "items": ["Iron Sword"], "lv": 2,
				"hp": 21, "str": 6, "dex": 6, "agi": 7, "lck": 4, "def": 4, "mp": 1, "mov": 5,
				"growths": {"hp": 75, "str": 45, "dex": 45, "agi": 45, "lck": 35, "def": 25, "mp": 15}},
			{"name": "Galley", "cell": Vector2i(8, 9), "class": "Galley", "items": ["Iron Bow"], "lv": 2,
				"hp": 26, "str": 6, "dex": 5, "agi": 2, "lck": 2, "def": 6, "mp": 0, "mov": 5,
				"growths": {"hp": 85, "str": 40, "dex": 35, "agi": 10, "lck": 25, "def": 40, "mp": 5}},
		],
		"enemies": [
			{"name": "Bandit", "cell": Vector2i(5, 4), "class": "Brigand", "items": ["Iron Axe"], "lv": 2,
				"hp": 21, "str": 6, "dex": 3, "agi": 6, "lck": 1, "def": 3, "mp": 0, "mov": 6,
				"ai": {"preset": "ambusher"}},
			{"name": "Bandit", "cell": Vector2i(2, 7), "class": "Brigand", "items": ["Woodcutter", "Hatchet"], "lv": 2,
				"hp": 21, "str": 6, "dex": 3, "agi": 6, "lck": 1, "def": 3, "mp": 0, "mov": 6,
				"ai": {"preset": "sleeper"}},
			{"name": "Lancer", "cell": Vector2i(9, 2), "class": "Cavalry", "items": ["Iron Spear"], "lv": 2,
				"hp": 20, "str": 6, "dex": 5, "agi": 5, "lck": 2, "def": 5, "mp": 1, "mov": 7},
			{"name": "Harpy", "cell": Vector2i(10, 0), "class": "Archer", "race": "Harpy", "items": ["Iron Bow"], "lv": 3,
				"hp": 20, "str": 6, "dex": 6, "agi": 8, "lck": 2, "def": 4, "mp": 2, "mov": 7},
			{"name": "Naga", "cell": Vector2i(8, 4), "class": "Footman", "race": "Naga", "items": ["Javelin"], "lv": 2,
				"hp": 18, "str": 5, "dex": 6, "agi": 7, "lck": 3, "def": 3, "mp": 4, "mov": 5,
				"ai": {"preset": "ambusher"}},
			{"name": "Galley", "cell": Vector2i(12, 1), "class": "Galley", "items": ["Iron Bow"], "lv": 2,
				"hp": 24, "str": 6, "dex": 5, "agi": 2, "lck": 0, "def": 6, "mp": 0, "mov": 4},
			{"name": "Galley", "cell": Vector2i(13, 7), "class": "Galley", "items": ["Iron Bow"], "lv": 2,
				"hp": 24, "str": 6, "dex": 5, "agi": 2, "lck": 0, "def": 6, "mp": 0, "mov": 4},
			{"name": "Captain", "cell": Vector2i(13, 4), "class": "Swashbuckler", "items": ["Steel Axe", "Hatchet"], "lv": 4,
				"hp": 26, "str": 8, "dex": 5, "agi": 5, "lck": 2, "def": 6, "mp": 2, "mov": 5,
				"ai": {"preset": "boss"}},
		],
	},
	"desert_outpost": {
		"name": "Desert Outpost",
		"description": "Sand, dunes, paths, houses and an oasis. Horses bog down\nin sand and dunes; paths are fast for everyone.",
		"layout": [
			"DDSSSSS.SSSSDDD",
			"DSS.H.===.H.SSD",
			"SS..H.=T=.H..SS",
			"S..===.=.===..S",
			"S..=.LL=LL.=..S",
			"SS.=.LLFLL.=.SS",
			"DS.===.=.===.SD",
			"DDS...H=H...SDD",
			"DDDS..S=S..SDDD",
			"DDDDSSS=SSSDDDD",
		],
		"players": [
			{"name": "Lord", "cell": Vector2i(7, 9), "class": "Swordsman", "lord": true, "items": ["Iron Sword", "Knife", "Potion"], "lv": 2,
				"hp": 20, "str": 6, "dex": 8, "agi": 9, "lck": 7, "def": 5, "mov": 5, "mp": 4,
				"growths": {"hp": 80, "str": 45, "dex": 50, "agi": 40, "lck": 45, "def": 30, "mp": 30}},
			{"name": "Nomad", "cell": Vector2i(6, 8), "class": "Nomad", "items": ["Iron Bow"], "lv": 2,
				"hp": 19, "str": 5, "dex": 7, "agi": 7, "lck": 4, "def": 4, "mov": 7, "mp": 2,
				"growths": {"hp": 65, "str": 40, "dex": 50, "agi": 45, "lck": 40, "def": 20, "mp": 15}},
			{"name": "Rider", "cell": Vector2i(8, 8), "class": "Equestrian", "items": ["Iron Sword"], "lv": 2,
				"hp": 22, "str": 7, "dex": 6, "agi": 6, "lck": 4, "def": 6, "mov": 7, "mp": 2,
				"growths": {"hp": 75, "str": 45, "dex": 40, "agi": 35, "lck": 35, "def": 30, "mp": 15}},
			{"name": "Scout", "cell": Vector2i(5, 9), "class": "Rogue", "items": ["Iron Sword", "Knife"], "lv": 2,
				"hp": 18, "str": 5, "dex": 9, "agi": 11, "lck": 6, "def": 3, "mov": 6, "mp": 2,
				"growths": {"hp": 65, "str": 35, "dex": 55, "agi": 65, "lck": 50, "def": 15, "mp": 20}},
			{"name": "Guard", "cell": Vector2i(7, 8), "class": "Guard", "items": ["Iron Spear"], "lv": 2,
				"hp": 24, "str": 8, "dex": 4, "agi": 2, "lck": 2, "def": 10, "mov": 4, "mp": 1,
				"growths": {"hp": 90, "str": 40, "dex": 30, "agi": 25, "lck": 30, "def": 55, "mp": 10}},
			{"name": "Cleric", "cell": Vector2i(9, 9), "class": "Cleric", "items": ["Quarterstaff"], "spells": ["Heal"], "lv": 1,
				"hp": 16, "str": 1, "int": 5, "dex": 5, "agi": 7, "lck": 6, "def": 1, "mov": 5, "mp": 12,
				"growths": {"hp": 50, "str": 10, "int": 55, "dex": 40, "agi": 45, "lck": 55, "def": 10, "mp": 40}},
		],
		"enemies": [
			{"name": "Warlord", "cell": Vector2i(7, 2), "class": "Swordsmaster", "items": ["Killing Edge"], "lv": 5,
				"hp": 28, "str": 8, "dex": 9, "agi": 9, "lck": 4, "def": 6, "mov": 5, "mp": 3,
				"ai": {"preset": "boss"}},
			{"name": "Archer", "cell": Vector2i(4, 1), "class": "Archer", "items": ["Iron Bow"], "lv": 2,
				"hp": 17, "str": 5, "dex": 5, "agi": 5, "lck": 1, "def": 2, "mov": 5, "mp": 1,
				"ai": {"preset": "turret"}},
			{"name": "Archer", "cell": Vector2i(10, 1), "class": "Archer", "items": ["Iron Bow"], "lv": 2,
				"hp": 17, "str": 5, "dex": 5, "agi": 5, "lck": 1, "def": 2, "mov": 5, "mp": 1,
				"ai": {"preset": "turret"}},
			{"name": "Footman", "cell": Vector2i(6, 2), "class": "Footman", "items": ["Pike", "Javelin"], "lv": 2,
				"hp": 19, "str": 6, "dex": 4, "agi": 4, "lck": 1, "def": 5, "mov": 5, "mp": 1,
				"ai": {"preset": "sentry"}},
			{"name": "Nomad", "cell": Vector2i(1, 1), "class": "Nomad", "items": ["Iron Bow"], "lv": 2,
				"hp": 18, "str": 5, "dex": 5, "agi": 6, "lck": 2, "def": 3, "mov": 7, "mp": 0},
			{"name": "Nomad", "cell": Vector2i(13, 1), "class": "Nomad", "items": ["Iron Bow"], "lv": 2,
				"hp": 18, "str": 5, "dex": 5, "agi": 6, "lck": 2, "def": 3, "mov": 7, "mp": 0},
			{"name": "Bandit", "cell": Vector2i(12, 4), "class": "Rogue", "items": ["Knife"], "lv": 2,
				"hp": 17, "str": 4, "dex": 6, "agi": 10, "lck": 3, "def": 2, "mov": 6, "mp": 1,
				"ai": {"preset": "coward", "targeting": "weakest"}},
		],
	},
	"frozen_pass": {
		"name": "Frozen Pass",
		"description": "Snow, ice, hills, mountains, thickets and a waterfall.\nClimbers take the hills, armor grips the ice, divers swim.",
		"layout": [
			"MMMhh**##**hhMM",
			"MMh***~v~***hMM",
			"Mh**#*~~~*#**hM",
			"h***##*~*##***h",
			"***iii*~*iii***",
			"**iiLLL~LLLii**",
			"*hiiLLLLLLLiih*",
			"*h*iiiiiiiiii*h",
			"hh***F...F***hh",
			"Mhh**F...F**hhM",
		],
		"players": [
			{"name": "Lord", "cell": Vector2i(7, 9), "class": "Swordsman", "lord": true, "items": ["Iron Sword", "Knife", "Potion"], "lv": 2,
				"hp": 20, "str": 6, "dex": 8, "agi": 9, "lck": 7, "def": 5, "mov": 5, "mp": 4,
				"growths": {"hp": 80, "str": 45, "dex": 50, "agi": 40, "lck": 45, "def": 30, "mp": 30}},
			{"name": "Guard", "cell": Vector2i(6, 9), "class": "Guard", "items": ["Iron Spear", "Javelin"], "lv": 2,
				"hp": 24, "str": 8, "dex": 4, "agi": 2, "lck": 2, "def": 10, "mov": 4, "mp": 1,
				"growths": {"hp": 90, "str": 40, "dex": 30, "agi": 25, "lck": 30, "def": 55, "mp": 10}},
			{"name": "Climber", "cell": Vector2i(8, 9), "class": "Brigand", "items": ["Hammer", "Hatchet"], "lv": 2,
				"hp": 24, "str": 8, "dex": 4, "agi": 5, "lck": 3, "def": 4, "mov": 5, "mp": 0,
				"growths": {"hp": 85, "str": 55, "dex": 35, "agi": 30, "lck": 30, "def": 25, "mp": 10}},
			{"name": "Diver", "cell": Vector2i(7, 8), "class": "Corsair", "items": ["Iron Sword"], "lv": 2,
				"hp": 20, "str": 6, "dex": 7, "agi": 8, "lck": 5, "def": 4, "mov": 5, "mp": 2,
				"growths": {"hp": 70, "str": 40, "dex": 45, "agi": 50, "lck": 40, "def": 20, "mp": 20}},
			{"name": "Archer", "cell": Vector2i(6, 8), "class": "Archer", "items": ["Iron Bow"], "lv": 2,
				"hp": 18, "str": 5, "dex": 7, "agi": 6, "lck": 4, "def": 3, "mov": 5, "mp": 1,
				"growths": {"hp": 60, "str": 40, "dex": 50, "agi": 60, "lck": 50, "def": 15, "mp": 25}},
			{"name": "Cleric", "cell": Vector2i(8, 8), "class": "Cleric", "items": ["Quarterstaff"], "spells": ["Heal"], "lv": 1,
				"hp": 16, "str": 1, "int": 5, "dex": 5, "agi": 7, "lck": 6, "def": 1, "mov": 5, "mp": 12,
				"growths": {"hp": 50, "str": 10, "int": 55, "dex": 40, "agi": 45, "lck": 55, "def": 10, "mp": 40}},
		],
		"enemies": [
			{"name": "Chieftain", "cell": Vector2i(7, 0), "class": "Berserker", "items": ["Steel Axe"], "lv": 5,
				"hp": 30, "str": 9, "dex": 5, "agi": 6, "lck": 2, "def": 6, "mov": 5, "mp": 1,
				"ai": {"preset": "boss"}},
			{"name": "Raider", "cell": Vector2i(3, 0), "class": "Brigand", "items": ["Iron Axe"], "lv": 2,
				"hp": 22, "str": 7, "dex": 3, "agi": 4, "lck": 1, "def": 3, "mov": 5, "mp": 0,
				"ai": {"preset": "ambusher"}},
			{"name": "Raider", "cell": Vector2i(12, 0), "class": "Brigand", "items": ["Iron Axe"], "lv": 2,
				"hp": 22, "str": 7, "dex": 3, "agi": 4, "lck": 1, "def": 3, "mov": 5, "mp": 0,
				"ai": {"preset": "ambusher"}},
			{"name": "Archer", "cell": Vector2i(1, 2), "class": "Archer", "items": ["Iron Bow"], "lv": 2,
				"hp": 17, "str": 5, "dex": 5, "agi": 5, "lck": 1, "def": 2, "mov": 5, "mp": 1,
				"ai": {"preset": "turret"}},
			{"name": "Turret", "cell": Vector2i(13, 2), "class": "Turret", "items": ["Iron Bow"], "lv": 3,
				"hp": 22, "str": 6, "dex": 5, "agi": 2, "lck": 1, "def": 8, "mov": 4, "mp": 0,
				"ai": {"preset": "turret"}},
			{"name": "Naga", "cell": Vector2i(5, 5), "class": "Footman", "race": "Naga", "items": ["Iron Spear"], "lv": 2,
				"hp": 18, "str": 5, "dex": 6, "agi": 7, "lck": 3, "def": 3, "mov": 5, "mp": 4,
				"ai": {"preset": "ambusher"}},
			{"name": "Guard", "cell": Vector2i(4, 4), "class": "Guard", "items": ["Iron Spear"], "lv": 2,
				"hp": 22, "str": 7, "dex": 3, "agi": 2, "lck": 1, "def": 9, "mov": 4, "mp": 0},
		],
	},
	"castle_keep": {
		"name": "Castle Keep",
		"description": "Indoors: walls, pillars, pits and fences. Mounted units\nare slow inside; a Wraith walks through walls.",
		"layout": [
			"XXXXXXXXXXXXXXX",
			"X___I__T__I___X",
			"X_____ccc_____X",
			"X__I__ccc__I__X",
			"XXX_X_ccc_X_XXX",
			"X_OO__ccc__OO_X",
			"X_OO|_ccc_|OO_X",
			"X___|_ccc_|___X",
			"X_____ccc_____X",
			"XXXXXX___XXXXXX",
		],
		"players": [
			{"name": "Lord", "cell": Vector2i(7, 9), "class": "Swordsman", "lord": true, "items": ["Iron Sword", "Knife", "Potion"], "lv": 2,
				"hp": 20, "str": 6, "dex": 8, "agi": 9, "lck": 7, "def": 5, "mov": 5, "mp": 4,
				"growths": {"hp": 80, "str": 45, "dex": 50, "agi": 40, "lck": 45, "def": 30, "mp": 30}},
			{"name": "Pegasus", "cell": Vector2i(6, 9), "class": "Flier", "items": ["Iron Spear", "Javelin"], "lv": 2,
				"hp": 17, "str": 5, "dex": 7, "agi": 10, "lck": 6, "def": 3, "mov": 7, "mp": 6,
				"growths": {"hp": 60, "str": 35, "dex": 50, "agi": 60, "lck": 50, "def": 15, "mp": 45}},
			{"name": "Rider", "cell": Vector2i(8, 9), "class": "Equestrian", "items": ["Iron Sword"], "lv": 2,
				"hp": 22, "str": 7, "dex": 6, "agi": 6, "lck": 4, "def": 6, "mov": 7, "mp": 2,
				"growths": {"hp": 75, "str": 45, "dex": 40, "agi": 35, "lck": 35, "def": 30, "mp": 15}},
			{"name": "Blade", "cell": Vector2i(7, 8), "class": "Swordsman", "items": ["Iron Sword", "Silver Sword"], "lv": 2,
				"hp": 20, "str": 6, "dex": 9, "agi": 9, "lck": 5, "def": 4, "mov": 5, "mp": 2,
				"growths": {"hp": 70, "str": 40, "dex": 55, "agi": 55, "lck": 40, "def": 20, "mp": 20}},
			{"name": "Archer", "cell": Vector2i(6, 8), "class": "Archer", "items": ["Iron Bow"], "lv": 2,
				"hp": 18, "str": 5, "dex": 7, "agi": 6, "lck": 4, "def": 3, "mov": 5, "mp": 1,
				"growths": {"hp": 60, "str": 40, "dex": 50, "agi": 60, "lck": 50, "def": 15, "mp": 25}},
			{"name": "Cleric", "cell": Vector2i(8, 8), "class": "Cleric", "items": ["Quarterstaff"], "spells": ["Heal"], "lv": 1,
				"hp": 16, "str": 1, "int": 5, "dex": 5, "agi": 7, "lck": 6, "def": 1, "mov": 5, "mp": 12,
				"growths": {"hp": 50, "str": 10, "int": 55, "dex": 40, "agi": 45, "lck": 55, "def": 10, "mp": 40}},
		],
		"enemies": [
			{"name": "King", "cell": Vector2i(7, 1), "class": "Swordsmaster", "items": ["Killing Edge", "Iron Sword"], "lv": 6,
				"hp": 30, "str": 9, "dex": 10, "agi": 9, "lck": 5, "def": 7, "mov": 5, "mp": 4,
				"ai": {"preset": "boss"}},
			{"name": "Archer", "cell": Vector2i(4, 1), "class": "Archer", "items": ["Iron Bow"], "lv": 2,
				"hp": 17, "str": 5, "dex": 5, "agi": 5, "lck": 1, "def": 2, "mov": 5, "mp": 1,
				"ai": {"preset": "turret"}},
			{"name": "Archer", "cell": Vector2i(10, 1), "class": "Archer", "items": ["Iron Bow"], "lv": 2,
				"hp": 17, "str": 5, "dex": 5, "agi": 5, "lck": 1, "def": 2, "mov": 5, "mp": 1,
				"ai": {"preset": "turret"}},
			{"name": "Guard", "cell": Vector2i(3, 2), "class": "Guard", "items": ["Iron Spear"], "lv": 3,
				"hp": 24, "str": 7, "dex": 4, "agi": 2, "lck": 1, "def": 10, "mov": 4, "mp": 0,
				"ai": {"preset": "sentry"}},
			{"name": "Wraith", "cell": Vector2i(1, 1), "class": "Wraith", "items": ["Iron Sword"], "lv": 3,
				"hp": 18, "str": 6, "dex": 6, "agi": 8, "lck": 0, "def": 3, "mov": 5, "mp": 6},
			{"name": "Harpy", "cell": Vector2i(12, 5), "class": "Archer", "race": "Harpy", "items": ["Iron Bow"], "lv": 2,
				"hp": 17, "str": 5, "dex": 6, "agi": 9, "lck": 3, "def": 2, "mov": 6, "mp": 3,
				"ai": {"preset": "ambusher"}},
			{"name": "Footman", "cell": Vector2i(12, 7), "class": "Footman", "items": ["Iron Spear", "Javelin"], "lv": 2,
				"hp": 19, "str": 6, "dex": 4, "agi": 4, "lck": 1, "def": 5, "mov": 5, "mp": 1,
				"ai": {"preset": "ambusher"}},
		],
	},
	"ruined_fort": {
		"name": "Ruined Fort",
		"description": "Breakable terrain: a cracked wall and fence, a locked door
(the Scout opens it) and trunks to fell across the river.",
		"layout": [
			"XXXXXXX...~....",
			"X__T__X...~..F.",
			"X_____x...~Y...",
			"X_____X...~....",
			"XXX+XXX.|.~....",
			"......../.~Y...",
			"........|.~....",
			".F......|.~..F.",
			"..........~....",
			"..........~....",
		],
		"objects": [
			{"type": "chest", "cell": Vector2i(1, 3), "item": "Silver Sword"},
		],
		"players": [
			{"name": "Lord", "cell": Vector2i(1, 8), "class": "Swordsman", "lord": true, "items": ["Iron Sword", "Potion"], "lv": 2,
				"hp": 20, "str": 6, "dex": 8, "agi": 9, "lck": 7, "def": 5, "mov": 5, "mp": 4,
				"growths": {"hp": 80, "str": 45, "dex": 50, "agi": 40, "lck": 45, "def": 30, "mp": 30}},
			{"name": "Fighter", "cell": Vector2i(2, 8), "class": "Axeman", "items": ["Iron Axe", "Hammer"], "lv": 2,
				"hp": 24, "str": 7, "dex": 4, "agi": 5, "lck": 3, "def": 3, "mp": 0, "mov": 5,
				"growths": {"hp": 80, "str": 60, "dex": 40, "agi": 20, "lck": 45, "def": 25, "mp": 15}},
			{"name": "Scout", "cell": Vector2i(1, 9), "class": "Rogue", "items": ["Iron Sword"], "lv": 2,
				"hp": 17, "str": 4, "dex": 7, "agi": 10, "lck": 6, "def": 2, "mp": 2, "mov": 6,
				"growths": {"hp": 60, "str": 30, "dex": 50, "agi": 65, "lck": 50, "def": 15, "mp": 25}},
			{"name": "Archer", "cell": Vector2i(2, 9), "class": "Archer", "items": ["Iron Bow"], "lv": 2,
				"hp": 18, "str": 5, "dex": 7, "agi": 6, "lck": 4, "def": 3, "mov": 5, "mp": 1,
				"growths": {"hp": 60, "str": 40, "dex": 50, "agi": 60, "lck": 50, "def": 15, "mp": 25}},
			{"name": "Knight", "cell": Vector2i(3, 9), "class": "Guard", "items": ["Iron Spear", "Javelin"], "lv": 2,
				"hp": 23, "str": 7, "dex": 4, "agi": 2, "lck": 2, "def": 9, "mp": 1, "mov": 4,
				"growths": {"hp": 90, "str": 40, "dex": 30, "agi": 30, "lck": 35, "def": 55, "mp": 15}},
		],
		"enemies": [
			{"name": "Warden", "cell": Vector2i(3, 1), "class": "Guard", "items": ["Iron Spear"], "lv": 4,
				"hp": 26, "str": 8, "dex": 5, "agi": 3, "lck": 2, "def": 10, "mov": 4, "mp": 0,
				"ai": {"preset": "boss"}},
			{"name": "Archer", "cell": Vector2i(13, 3), "class": "Archer", "items": ["Iron Bow"], "lv": 2,
				"hp": 17, "str": 5, "dex": 5, "agi": 5, "lck": 1, "def": 2, "mov": 5, "mp": 1,
				"ai": {"preset": "turret"}},
			{"name": "Brigand", "cell": Vector2i(13, 7), "class": "Brigand", "items": ["Iron Axe"], "lv": 2,
				"hp": 20, "str": 5, "dex": 1, "agi": 4, "lck": 0, "def": 3, "mp": 0, "mov": 5,
				"ai": {"preset": "sentry"}},
			{"name": "Brigand", "cell": Vector2i(12, 1), "class": "Brigand", "items": ["Iron Axe", "Hatchet"], "lv": 2,
				"hp": 20, "str": 5, "dex": 1, "agi": 4, "lck": 0, "def": 3, "mp": 0, "mov": 5,
				"ai": {"preset": "ambusher"}},
		],
	},
}


## A test map (DATA) or a campaign chapter (Chapters.DATA).
static func get_level(id: String) -> Dictionary:
	return DATA[id] if DATA.has(id) else Chapters.DATA[id]
